import * as THREE from 'three';
import type { GLTF } from 'three-stdlib';
import type { OrbitControls } from 'three-stdlib';
import type { FC } from 'react';

export type StripClubModelBaseProps = JSX.IntrinsicElements['group'];

export interface StripClubModelProps extends StripClubModelBaseProps {
  cameraTarget: THREE.SkinnedMesh;
}

export type StripClubModelComponent = FC<StripClubModelProps>;

export type GLTFResult = GLTF & {
  nodes: {
    speaker: THREE.Mesh;
    speaker003: THREE.Mesh;
    speaker004: THREE.Mesh;
    speaker005: THREE.Mesh;
    speaker006: THREE.Mesh;
    speaker007: THREE.Mesh;
    mixer_speaker001: THREE.Mesh;
    mixer_speaker: THREE.Mesh;
    mixer: THREE.Mesh;
    DoorFrame: THREE.Mesh;
    Door: THREE.Mesh;
    Handle_Front: THREE.Mesh;
    DoorFrame001: THREE.Mesh;
    Door001: THREE.Mesh;
    Handle_Front001: THREE.Mesh;
    curtain: THREE.Mesh;
    curtain001: THREE.Mesh;
    curtain002: THREE.Mesh;
    curtain003: THREE.Mesh;
    curtain004: THREE.Mesh;
    barstool008: THREE.Mesh;
    Circle018: THREE.Mesh;
    barstool: THREE.Mesh;
    Circle004: THREE.Mesh;
    barstool003: THREE.Mesh;
    Circle008: THREE.Mesh;
    barstool005: THREE.Mesh;
    Circle012: THREE.Mesh;
    barstool002: THREE.Mesh;
    Circle007: THREE.Mesh;
    barstool004: THREE.Mesh;
    Circle011: THREE.Mesh;
    barstool006: THREE.Mesh;
    Circle014: THREE.Mesh;
    barstool007: THREE.Mesh;
    Circle016: THREE.Mesh;
    barstool001: THREE.Mesh;
    Circle019: THREE.Mesh;
    barstool009: THREE.Mesh;
    Circle021: THREE.Mesh;
    neon_sign_neon_shoe: THREE.Mesh;
    neon_sign_happy_hour_sign: THREE.Mesh;
    neon_sign_fun_neon: THREE.Mesh;
    neon_sign_live_music_sign: THREE.Mesh;
    stay_wild: THREE.Mesh;
    neon_sign_neon_shoe001: THREE.Mesh;
    bar_wall001: THREE.Mesh;
    bar_wall002: THREE.Mesh;
    bar_wall: THREE.Mesh;
    ceiling_lights: THREE.Mesh;
    ceiling_lights001: THREE.Mesh;
    ceiling_lights002: THREE.Mesh;
    ceiling_lights003: THREE.Mesh;
    table008: THREE.Mesh;
    table009: THREE.Mesh;
    table007: THREE.Mesh;
    table006: THREE.Mesh;
    table004: THREE.Mesh;
    table005: THREE.Mesh;
    table001: THREE.Mesh;
    table002: THREE.Mesh;
    table003: THREE.Mesh;
    metal_chair030: THREE.Mesh;
    metal_chair031: THREE.Mesh;
    metal_chair029: THREE.Mesh;
    metal_chair008: THREE.Mesh;
    metal_chair009: THREE.Mesh;
    metal_chair010: THREE.Mesh;
    metal_chair011: THREE.Mesh;
    metal_chair012: THREE.Mesh;
    metal_chair013: THREE.Mesh;
    metal_chair004: THREE.Mesh;
    metal_chair005: THREE.Mesh;
    metal_chair006: THREE.Mesh;
    metal_chair002: THREE.Mesh;
    metal_chair003: THREE.Mesh;
    metal_chair007: THREE.Mesh;
    metal_chair001: THREE.Mesh;
    metal_chair028: THREE.Mesh;
    metal_chair014: THREE.Mesh;
    metal_chair015: THREE.Mesh;
    metal_chair016: THREE.Mesh;
    metal_chair017: THREE.Mesh;
    metal_chair018: THREE.Mesh;
    metal_chair019: THREE.Mesh;
    metal_chair032: THREE.Mesh;
    metal_chair025: THREE.Mesh;
    metal_chair026: THREE.Mesh;
    metal_chair020: THREE.Mesh;
    metal_chair021: THREE.Mesh;
    metal_chair022: THREE.Mesh;
    metal_chair023: THREE.Mesh;
    metal_chair024: THREE.Mesh;
    stage_down: THREE.Mesh;
    stage_up: THREE.Mesh;
    pole: THREE.Mesh;
    walls: THREE.Mesh;
    walls005: THREE.Mesh;
    ceiling001: THREE.Mesh;
    Stairs: THREE.Mesh;
    bar_counter_bottom: THREE.Mesh;
    bar_counter_top: THREE.Mesh;
    floor: THREE.Mesh;
  };
  materials: {
    floor: THREE.MeshStandardMaterial;
  };
};
export type OrbitControlsImpl = OrbitControls;
